### ISSUE TITLE
json fileとして保存してフロントで扱い安くデータを保持したい

### ISSUE THREAD

**Issue by Jumpo-523** [Code-for-Funabashi/open_data_parser#1]
csvファイルにした施設データ（暫定版）を改修する

1. csv形式→json形式
2. 下記のように`['施設名', '住所', '電話番号(代表)', 'lat', 'lng', ’施設タイプ’]`のカラム名を翻訳しました

要件こんな感じでいいですかね？@aca-ta 

```
[{'facility_name': '若松幼稚園',
  'address': '〒273-0013船橋市若松2-3-3',
  'phone_number': '047-431-7751',
  'lat': 35.6786083,
  'lng': 139.9965109,
  'facility_type': '一時保育'},
 {'facility_name': 'まなびの森保育園\u3000船橋競馬場駅前',
  'address': '〒273-0003船橋市宮本9-1-11',
  'phone_number': '047-402-4402',
  'lat': 35.6895785,
  'lng': 139.9970893,
  'facility_type': '一時保育'},
...
]
```

**Comment by aca-ta** [comment]
こんな感じが良いかなと思いました
```json
[{"name": "若松幼稚園",
  "lat": 35.6786083,
  "lng": 139.9965109,
  "details": {
    "address": "〒273-0013船橋市若松2-3-3",
    "phone_number": "047-431-7751"
  }
}]
```
地点データとして汎用的に使えるスキーマで考えてみました。
- `facility_name` は 施設名である事は自明なので `name` で良いかなと思います
- `facility_type` は全てのオブジェクトで同じ値をもたせるのももったいないので、ここでは持たず、URLと一緒にフロント側で定義するで良いと思います(地物の種類によってファイルが異なる前提で考えてます)
- optionalな項目はdetailsという項目を設けてそこに入れるのが良いかなと思いました
    - 地物によっては電話番号がなかったり、逆に待機児童数的な項目が生えたりすると思うので、そういうのはここにつっこむイメージ

**Comment by Jumpo-523** [comment]
ありがとうございます！！！

>(地物の種類によってファイルが異なる前提で考えてます)
把握しました！
＞地物によっては電話番号がなかったり、逆に待機児童数的な項目が生えたりすると思う
なるほど、detailsの方が拡張しやすいですね。。！承知です！
